name: applicationpfe
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  firebase_auth: ^4.19.5
  rounded_loading_button_plus: ^3.0.1
  page_transition: ^2.1.0
  cloud_firestore: ^4.17.3
  achievement_view: ^1.0.1
  syncfusion_flutter_gauges: ^25.2.4
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Digital7
      fonts:
        - asset: assets/fonts/digital-7.ttf
        - asset: assets/fonts/digital-7 (italic).ttf
          style: italic
        - asset: assets/fonts/digital-7 (mono).ttf
        - asset: assets/fonts/digital-7 (mono italic).ttf
          style: italic
