name: applicationpfe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_database: ^11.0.2
  firebase_auth: ^5.1.1
  rounded_loading_button_plus: ^3.0.1
  page_transition: ^2.1.0
  cloud_firestore: ^5.0.2
  achievement_view: ^1.0.1
  syncfusion_flutter_gauges: ^26.1.39
  percent_indicator: ^4.2.3
  get: 4.6.6
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: assets.dart

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Digital7
      fonts:
        - asset: assets/fonts/digital-7.ttf
        - asset: assets/fonts/digital-7 (italic).ttf
          style: italic
        - asset: assets/fonts/digital-7 (mono).ttf
        - asset: assets/fonts/digital-7 (mono italic).ttf
          style: italic
