name: applicationpfe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter_animate: ^4.5.0
  chewie: ^1.8.1
  achievement_view: ^1.0.1
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.6
  flutter_svg: ^1.1.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  video_player: ^2.9.1
  firebase_database: ^11.0.2
  flutter:
    sdk: flutter
  flutter_animated_splash: ^0.0.10
  get: 4.6.6
  get_storage: ^2.1.1
  page_transition: ^2.1.0
  percent_indicator: ^4.2.3
  rounded_loading_button_plus: ^3.0.1
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_gauges: ^26.1.39
  font_awesome_flutter: ^10.7.0
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  hooks_riverpod: ^2.5.1
  flutter_map: ^7.0.2
  location: ^7.0.0
  latlong2: ^0.9.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/videos/1/1.mp4
    - assets/videos/1/2.mp4
    - assets/videos/1/3.mp4
    - assets/images/
  fonts:
    - family: Digital7
      fonts:
        - asset: assets/fonts/digital-7.ttf
        - asset: assets/fonts/digital-7 (italic).ttf
          style: italic
        - asset: assets/fonts/digital-7 (mono).ttf
        - asset: assets/fonts/digital-7 (mono italic).ttf
          style: italic
